# Generated by Django 3.1.2 on 2020-10-30 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinfo',
            name='developer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='最小值为 1')], verbose_name='接口开发者'),
        ),
        migrations.AddField(
            model_name='caseinfo',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='是否通知开发者'),
        ),
        migrations.AddField(
            model_name='project',
            name='notify',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否发送通知'),
        ),
        migrations.AddField(
            model_name='report',
            name='developer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='最小值为 1')], verbose_name='接口开发者'),
        ),
        migrations.AddField(
            model_name='report',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='是否通知开发者'),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='email',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(64, message='最大长度为 64'), django.core.validators.EmailValidator(message='请输入正确的邮箱账号')], verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(16, message='最大长度为 16'), django.core.validators.RegexValidator(message='请输入正确的手机号', regex='^1[3,4,5,7,8]\\d{9}$')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(64, message='最大长度为 64'), django.core.validators.EmailValidator(message='请输入正确的邮箱账号')], verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(16, message='最大长度为 16'), django.core.validators.RegexValidator(message='请输入正确的手机号', regex='^1[3,4,5,7,8]\\d{9}$')], verbose_name='手机号'),
        ),
        migrations.AddIndex(
            model_name='caseinfo',
            index=models.Index(fields=['owner', 'project_id', 'developer'], name='project_owner_developer_idx'),
        ),
    ]
