# Generated by Django 3.1.2 on 2020-12-24 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(32, message='最大长度为 32')], verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='caseinfo',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(255, message='最大长度为 255')], verbose_name='用例备注'),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='email',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(64, message='最大长度为 64'), django.core.validators.EmailValidator(message='请输入正确的邮箱账号')], verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(32, message='最大长度为 32')], verbose_name='联系人名称'),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(16, message='最大长度为 16'), django.core.validators.RegexValidator(message='请输入正确的手机号', regex='^1[3,4,5,7,8]\\d{9}$')], verbose_name='手机号'),
        ),
        migrations.AddConstraint(
            model_name='caseinfo',
            constraint=models.UniqueConstraint(fields=('owner', 'project_id', 'name'), name='case_owner_project_name_idx'),
        ),
    ]
