# Generated by Django 3.1.2 on 2020-11-06 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201030_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(255, message='最大长度为 255')], verbose_name='文件路径'),
            preserve_default=False,
        ),
    ]
