# Generated by Django 3.1.2 on 2020-11-10 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='remark',
            field=models.CharField(default=None, max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(255, message='最大长度为 255')], verbose_name='记录描述'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, message='最小值为 1')], verbose_name='等同于用例 id'),
        ),
    ]
