# Generated by Django 3.1.2 on 2020-12-25 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201225_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='developer',
            field=models.IntegerField(blank=True, null=True, verbose_name='接口开发者'),
        ),
        migrations.AlterField(
            model_name='caseinfo',
            name='expected_http_status',
            field=models.IntegerField(blank=True, default=200, null=True, validators=[django.core.validators.MinValueValidator(1, message='最小值为 1')], verbose_name='Http 状态码'),
        ),
    ]
