# Generated by Django 3.1.2 on 2020-12-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201225_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseinfo',
            name='check_step',
        ),
    ]
