# Generated by Django 3.1.2 on 2020-12-25 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_caseinfo_check_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='check_step',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='case_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='最小值为 1')], verbose_name='等同于用例 id'),
        ),
        migrations.AddField(
            model_name='report',
            name='delay',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='最小值为 0'), django.core.validators.MaxValueValidator(300, message='最大值为 300')], verbose_name='延迟执行时长, 单位秒, 最长延时五分钟即 300'),
        ),
        migrations.AddField(
            model_name='report',
            name='sample',
            field=models.JSONField(blank=True, null=True, verbose_name='结果示例，用于接口依赖时方便直接获得取值步骤'),
        ),
        migrations.AlterField(
            model_name='report',
            name='developer',
            field=models.IntegerField(blank=True, null=True, verbose_name='接口开发者'),
        ),
        migrations.AlterField(
            model_name='report',
            name='expected_http_status',
            field=models.IntegerField(blank=True, default=200, null=True, validators=[django.core.validators.MinValueValidator(1, message='最小值为 1')], verbose_name='Http 状态码'),
        ),
        migrations.AlterField(
            model_name='report',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='请求 host，没填会使用项目的'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(32, message='最大长度为 32')], verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='report',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(255, message='最大长度为 255')], verbose_name='用例备注'),
        ),
    ]
