# Generated by Django 3.1.2 on 2021-01-15 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201226_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseinfo',
            options={'ordering': ['sort', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='contactor',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='contactorgroup',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='filegroup',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='projectgroup',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='FAILED', max_length=8, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(8, message='最大长度为 8')], verbose_name='用例执行结果'),
        ),
    ]
