# Generated by Django 3.1.2 on 2021-01-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_caseinfo_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='notify',
        ),
    ]
