# Generated by Django 3.1.2 on 2021-01-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_report_notify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['sort', '-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='report_owner_record_idx',
        ),
    ]
