# Generated by Django 3.1.2 on 2021-01-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210127_0948'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['owner', 'record_id'], name='report_owner_record_idx'),
        ),
    ]
