# Generated by Django 3.1.2 on 2021-01-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210127_0949'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caseinfo',
            name='case_owner_project_name_idx',
        ),
    ]
