# Generated by Django 3.1.2 on 2021-01-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210127_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='response_content',
            field=models.JSONField(blank=True, null=True, verbose_name='响应状态'),
        ),
    ]
