# Generated by Django 3.1.2 on 2021-03-19 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210128_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactorgroup',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='caseinfo',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(64, message='最大长度为 64')], verbose_name='用例名称'),
        ),
    ]
