# Generated by Django 3.1.2 on 2021-03-19 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210319_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(64, message='最大长度为 64')], verbose_name='用例名称'),
        ),
        migrations.AddConstraint(
            model_name='caseinfo',
            constraint=models.UniqueConstraint(fields=('owner', 'project_id', 'name'), name='owner_project_name_idx'),
        ),
    ]
