# Generated by Django 3.1.2 on 2021-03-20 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210319_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(32, message='最大长度为 32')])),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(32, message='最大长度为 32')], verbose_name='角色名称')),
                ('role', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1, message='最小长度为 1'), django.core.validators.MaxLengthValidator(32, message='最大长度为 16')], verbose_name='角色')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255, message='最大长度为 255')], verbose_name='文件描述')),
                ('owner', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='最小值为 1')], verbose_name='分组拥有者')),
            ],
            options={
                'db_table': 'platform_role',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='role_owner_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('owner', 'role'), name='role_owner_role_idx'),
        ),
    ]
